Add logging statements when adjusting actor registry count
actor-framework/actor-framework pull request #1138
Opened 2020-08-27 11:37 UTC by lava

Add a debug statements printing the actor id whenever the running actor count is adjusted.

This speeds up debugging for errors where the running count does not reach zero at program shutdown but it is not clear which actor is still alive.

NOTE: The compatibility header is based on similar code I wrote at https://mesos.apache.org/api/latest/c++/3rdparty_2stout_2include_2stout_2attributes_8hpp_source.html . If CAF already requires a compiler with support for standard attributes this can also be removed to reduce cruft.

2020-08-27 11:59 UTC, Neverlord commented
1. Before adding an unnecessary macro workaround, you could have easily checked whether we use the attribute: `fgrep -R '[[maybe_unused]]' libcaf_*`
2. How is the new logging speeding up debugging over `grep 'TERMINATE\|SPAWN' my.log`?

2020-08-27 13:17 UTC, lava commented
Thanks for the reply. I actually did (1), but on the 0.17 branch since that's what we're currently using internally, so I did not get any results, and I didn't think to check again after rebasing.

For (2), it was not obvious to me what guarantees there are on the relationship between spawn()/terminate() and the registry. Not all spawned actors are registered, and from the docs it seemed like usage of the registry is intended to be somewhat dynamic, e.g. with middleman adding and removing actors as needed. Since shutdown is usually blocking on `await_running_count_equal(0)`, adding print statements directly in the registry strips away all abstraction and directly gives the offending actor id by subtracting the removed ids from the added ids.

2020-08-27 23:55 UTC, sourcedelica commented
I'm all in favor of making this easier to debug.  It's one of the things that trips up new CAF developers on our team pretty regularly.

2020-08-28 07:32 UTC, Neverlord commented
> I'm all in favor of making this easier to debug.

Me too. 😉

I'm just wondering whether we can advance things further. So far, this revealed two things for me:

> the relationship between spawn()/terminate() and the registry.

The counter is actually a system metric and has nothing to do with the registry. The counter is part of the registry for historical reasons only. So, I think it's about time we get that right in the API and move the counter up to the `actor_system`. The SPAWN/TERMINATE events are the right things to look at. It seems like there's only one information missing: whether the actor is hidden or not. Hidden actors simply don't increase the `running` count. I feel like properly documenting that and maybe providing a small Python script that spits out unterminated actors from a log would help more in the long run.

> ...  strips away all abstraction and directly gives the offending actor id by subtracting the removed ids from the added ids.

So, here's another idea. We already have the metric `caf.running-actors`. We could rename that to `caf.system.running-actors` (total number of actors in the system) and add a new `caf.actor.running` metric (number of running actor for one kind of actor). With that, once your actor system hangs, you simply enable metrics for your actors, fire up your application again and get to the offending actor(s) with one shot using `curl` (plus `grep`, maybe) rather than combing through the debug logs. Because not only do you need CAF debug logs otherwise, you also need to have a CAF version with debug logging builtin. Metrics are always available to you.

Once you know what you are looking for, you can dive into the post-mortem analysis with log files (which you may generate with other means that CAF logging).

2020-08-28 14:47 UTC, sourcedelica commented
Not having to build logging variant to debug this issue would be very nice.

2020-08-28 15:04 UTC, lava commented
Adding the information to the metrics sounds like a great plan. It might also be worth considering doing both, since having the information in the logs would probably make it easier to get it in non-interactive contexts (eg. a CI run, or when post-mortem debugging from a customer issue)

2020-08-28 15:06 UTC, Neverlord requested changes
Regardless of the other ideas mentioned to improve debugging, I think this is generally a useful addition. However, I do have a request regarding the code. Passing the actor ID in semantically makes no sense, since the function does nothing with it (other than logging). Please have `inc_running` and `dec_running` return the new value and log at the calling actor.

Both functions are called only in `libcaf_core/src/abstract_actor.cpp`, so it's just shifting code around a bit.

2020-08-31 11:21 UTC, lava commented
@Neverlord I just pushed an updated version of this PR that includes the changes you suggested, thanks for taking the time.

2020-09-01 05:58 UTC, merged

2020-09-01 05:59 UTC, Neverlord commented
Thanks for the PR! 👍