Remove windows from Cirrus. Add Github Action for Windows CI
actor-framework/actor-framework pull request #1434
Opened 2023-06-14 11:39 UTC by riemass

Draft, just to invoke the pipeline.

2023-06-14 11:40 UTC, riemass commented
GH Actions don't give us number of cores as an environment variable, like cirrus does. There are workarounds to invoke a custom script to fetch the number. I've left that part out for now.

2023-06-14 12:09 UTC, Neverlord requested changes
I would prefer keeping the `Visual Studio 17 2022` generator if at all possible. But it wouldn't be a showstopper.

2023-06-14 12:14 UTC, riemass commented
The tests failed because we can't locate robot framework. I'll fix that. Just wanted to point out that I'm glad we tested the check - it fails if the tests fail. (I actually wanted to trigger this manually to be sure)

2023-06-15 05:43 UTC, Neverlord approved these changes

2023-06-15 05:44 UTC, merged