Make actor mailboxes configurable
actor-framework/actor-framework pull request #1511
Opened 2023-07-29 12:56 UTC by Neverlord

- Add a new interface for actor mailboxes.
- Add a new interface for mailbox factories.
- Add a new parameter to the `actor_config` for setting a custom mailbox factory.

Closes #1473.

@riemass technically, this is breaking "public" API by removing a whole bunch of classes from `caf::intrusive`. However, I *highly* doubt that any user depends on classes in this namespace directly. So I took some liberties in streamlining everything under `caf::intrusive` and to get rid of a whole lot of cruft. This turned out to be a bit of a larger change set, but I tried to break up the overall work into smaller pieces of work and have one commit per chunk. So maybe reviewing the commit diffs one by one makes it easier to review.

2023-08-04 13:49 UTC, riemass requested changes
Great work. Now that I've went through the implementation, it seems a lot cleaner, not only because of the interface, but the code needed some segregation of concerns. 
Here are some points, as good as I could review them. 
Also, are there some pros/cons on why you axed the DRR stuff?

2023-08-04 13:49 UTC, riemass commented on libcaf_core/caf/intrusive/linked_list.hpp
> +        tail_.next = &(head_);
Not sure about the parentheses?
```suggestion
        CAF_ASSERT(head_.next == &tail_);
        tail_.next = &head_;
```

2023-08-04 14:22 UTC, Neverlord commented
> Also, are there some pros/cons on why you axed the DRR stuff?

To give a bit of context: the old design had messages and stream data flow through the same mailbox and the actor would then use DRR (deficit-round-robin) to make sure it somewhat evenly multiplexes the various inputs. It sounds like in theory, but it actually overcomplicated things because the mailbox did too many things. After switching to the new flow API, we simply no longer have any need for the DRR stuff and can use a much simpler implementation.

2023-08-04 15:39 UTC, Neverlord commented on libcaf_core/caf/intrusive/linked_list.hpp
> +  /// the last element in the queue or to `head_` if the queue is empty.
ACK on the `queue => list` rename, but the the dummy really is the past-the-end node, i.e., `end()` returns a pointer to `tail_`.

2023-08-05 07:38 UTC, riemass commented on libcaf_core/caf/intrusive/linked_list.hpp
> +  node_type tail_;
Could we add these changes, and then skip calling `init` in the default and rvalue ctors?

```suggestion
  node_type head_ = &tail_;

  /// Dummy past-the-last-element node. The `tail_->next` pointer is pointing to
  /// the last element in the list or to `head_` if the list is empty.
  node_type tail_ = &head_;
```

2023-08-05 07:42 UTC, riemass approved these changes
:1st_place_medal:

2023-08-05 08:28 UTC, riemass approved these changes
Great find in the last minute.

2023-08-05 08:45 UTC, merged