Update the minimum version of CMake and tidy up
actor-framework/actor-framework pull request #1551
Opened 2023-09-08 07:48 UTC by riemass

Tidied up some old CMake rules. 
Not so sure about setting the CMake policy max to 3.27 (current release) but it seems to compile without problems.

2023-09-08 09:13 UTC, riemass commented
The windows action started failing with `python3.exe: No module named robot` after the changes, which makes little sense to me. 
I've run the pipeline on another PR to check if it's related to the changes.

2023-09-09 06:43 UTC, Neverlord requested changes
Just some nitpicks.

2023-09-09 06:43 UTC, Neverlord commented on robot/CMakeLists.txt
> +
```suggestion

```

2023-09-09 06:43 UTC, Neverlord commented on robot/CMakeLists.txt
> +    "The python package 'robotframework' could not be found"
Please use the active voice:

```suggestion
    "Failed to import the 'robot' Python package"
```

2023-09-09 18:29 UTC, Neverlord approved these changes

2023-09-09 18:29 UTC, merged