Fix unordered_flat_map equality, add contains()
actor-framework/actor-framework pull request #1635
Opened 2023-10-31 20:21 UTC by Neverlord

I've made a pass over our `unordered_flat_map`.

2023-11-01 20:04 UTC, riemass requested changes
I'm all in for removing `operator<`, doesn't really make sense in an unordered container. I've made some minor suggestions below.

2023-11-01 20:04 UTC, riemass commented on libcaf_core/caf/unordered_flat_map.hpp
> +  iterator insert_or_assign(const_iterator, const key_type& key,
Same as above, hint would now be deprecated?

2023-11-02 07:40 UTC, Neverlord commented on libcaf_core/caf/unordered_flat_map.hpp
> +  iterator insert(const_iterator, value_type x) {
The class is supposed to be a drop-in replacement for STL map types. Even though we don't do something with the hint, it's still imperative that we provide the STL interface. 🙂

2023-11-02 07:42 UTC, Neverlord commented on libcaf_core/caf/unordered_flat_map.test.cpp
> +  SECTION("at() accesses existing elements or inserts new ones") {
Yeah, that comment is blatantly wrong. Calling `at()` will throw if no such element exists. Good catch.

2023-11-02 07:44 UTC, Neverlord commented on libcaf_core/caf/unordered_flat_map.hpp
> +      erase(i);
Done.

2023-11-02 11:19 UTC, riemass approved these changes

2023-11-02 12:59 UTC, merged