Fix compilation error on MSVC
actor-framework/actor-framework pull request #1671
Opened 2023-11-18 09:54 UTC by Neverlord

Closes #1669.

There are still a lot of warnings on MSVC when building DLL's, but at least this patch makes CAF compile and link.

2023-11-18 12:13 UTC, riemass requested changes
Looks good. Asking about some nits, and what happened to `json.test.cpp`?

2023-11-19 10:16 UTC, Neverlord commented on CMakeLists.txt
> +                             $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
Sure, this is for finding the CAF headers of the component. As you have guessed, the binary directory is for finding generated code.

2023-11-20 11:39 UTC, Neverlord commented
> what happened to `json.test.cpp`?

That test got the axe, because it touches internals that we don't want to export. So it was either adding `CAF_CORE_EXPORT` to purely internal functions that we really don't want to export or just removing the test. I've opted for the latter, because the all of the public API types also have their own tests and we should do the testing there anyways.

2023-11-20 12:18 UTC, riemass approved these changes

2023-11-20 13:29 UTC, merged