Increase Prometheus coverage
actor-framework/actor-framework pull request #1689
Opened 2023-12-13 09:35 UTC by riemass

It seems we only use Prometheus in `robot/middleman/driver.cpp`. 

The reason we have so low coverage for Prometheus is that the `robot` folder is in the ignore list. Bad news is that removing the ignore on this folder this will also expect the drivers to be covered, so it's best to let the pipeline pass once and see the result.

2023-12-13 09:42 UTC, Neverlord commented
Even if the `robot` folder itself is ignored, the coverage from the other folders will still be counted. So this change will only add noise.

Are you maybe confusing the `caf.io` and the `caf.net` Prometheus implementation? The test you mention will cover the Prometheus Broker and has nothing to do with the implementation in `caf.net` https://app.codecov.io/gh/actor-framework/actor-framework/blob/master/libcaf_io%2Fcaf%2Fdetail%2Fprometheus_broker.cpp.

We simply don't have tests yet that execute the `caf.net` Prometheus code.

2023-12-13 14:26 UTC, riemass commented
You're right, I got the `net` and `io` drivers mixed up. I've enabled Prometheus in our `caf::net` robot tests to see the result.

2023-12-13 22:36 UTC, riemass commented
The `codecov` shows 100% on `prometheus.hpp/cpp` now. @Neverlord can I leave the test in `rest.robot`, or should I factor it out to a new file?

2023-12-14 07:38 UTC, Neverlord requested changes

2023-12-14 07:38 UTC, Neverlord commented on robot/http/rest.robot
> +${PR_HTTP_BAD_URL}      http://localhost:55515/foobar
Please use port 55516. This will collide when running test suites in parallel.

2023-12-14 07:39 UTC, Neverlord commented
> can I leave the test in `rest.robot`, or should I factor it out to a new file?

Can stay, just use a different port. Also, please squash the commits since the changes of the first commit have been reverted anyways.

2023-12-14 08:54 UTC, riemass commented
Rebased and squashed.

2023-12-14 09:55 UTC, Neverlord approved these changes

2023-12-14 09:55 UTC, merged