Add new logging API for events with custom fields
actor-framework/actor-framework pull request #1695
Opened 2023-12-15 18:43 UTC by Neverlord

Closes #1654.

2023-12-17 21:08 UTC, riemass requested changes
My only review item is that some `field` member functions aren't covered in tests. Otherwise looks good and can be merged. 

What I don't like is that we have the cost of calling 'logger::trace' while running on a less verbose logger. Things like `logger::accepts` are virtual function calls. What do you think of benchmarking the macro based API vs the new API for ~5 million log messages?

There are a few loose ends. I think we should update the manual with the new logger API before the release. Also when we integrate this, we should remove the macro logs from our  side to lead with a good example for the users. I grepped the `examples` folder for the word `log` and it seems like we don't have any user logging examples in place. 

And finally a feature request for structured logging, stuff like:
```
auto response = my_future.get();
logger::debug("app", "Received response.", response);
```
It should be possible to make this with our inspect API and map the struct to fields lazily.
Solutions like 
```
logger::debug("app", "Received response.", to_string(response));
```
should be discouraged because we pay the price for stratification at call site, even when we don't log this verbosity. 

The last couple of PRs are great progress and I was glad to review them. Looking forward for version v1.0. :steam_locomotive: :train: :train:.

2023-12-18 07:40 UTC, Neverlord commented on libcaf_core/caf/log_event.cpp
> +  auto* resource = &copy->resource_;
No, the resource is per-event.

2023-12-18 08:07 UTC, Neverlord commented
> My only review item is that some `field` member functions aren't covered in tests. Otherwise looks good and can be merged.

Pushes a new test that should cover the missing blocks.

> What I don't like is that we have the cost of calling 'logger::trace' while running on a less verbose logger. Things like `logger::accepts` are virtual function calls. What do you think of benchmarking the macro based API vs the new API for ~5 million log messages?

Tracing is definitely expensive, that's why I'd rather not use `logger::trace` directly (cf. #1652):

> The only logging that I would still keep behind a CMake build option is trace logging. Trace logs are expensive and traces into internal CAF functions are (with some very rare exceptions) only useful when working on CAF itself. I think it's perfectly fine to require custom builds for this use case.

That being said, benchmarking is always a good idea. But we'd have to compare to the 0.19.4 implementation.

> There are a few loose ends. I think we should update the manual with the new logger API before the release. Also when we integrate this, we should remove the macro logs from our side to lead with a good example for the users. I grepped the `examples` folder for the word `log` and it seems like we don't have any user logging examples in place.

Yes, switching to the new functions is definitely a next step. We can also think about deprecating the macros with 1.0.

> And finally a feature request for structured logging, stuff like:
> 
> ```
> auto response = my_future.get();
> logger::debug("app", "Received response.", response);
> ```
> 
> It should be possible to make this with our inspect API and map the struct to fields lazily.

Full ack. The `detail::format` indirection can probably wrap types that are inspectable but don't specialize `std::formatter`. For this, we'll probably have to re-implement `detail::stringification_inspector` to work on output iterators. Otherwise, we'll also produce an intermediary string.

2023-12-18 08:20 UTC, Neverlord commented on libcaf_core/caf/log_event.cpp
> +                              chunked_string str) {
Done. Thanks for keeping me honest on the tests. 🙂

2023-12-18 22:08 UTC, riemass approved these changes
This looks good now. Full ack on deprecating log macros with 1.0.

2023-12-19 08:26 UTC, merged