Implementation hiding of `caf::net` protocol specific classes
actor-framework/actor-framework pull request #1824
Opened 2024-03-22 14:40 UTC by riemass

As agreed, the low hanging classes from `caf::net` are now interfaces, with imlementation hidden in the translation units. One commit per class and no functional changes. 

Open question to consider as a followup are:
- classes `octest_stream::transport` and `ssl::transport`, 
- `net::socket_manager` could probably be hidden as well with some effort. 

Relates #1254.

2024-03-22 15:10 UTC, Neverlord requested changes
Just some nitpicks. Thanks for taking care of this!

2024-03-22 15:10 UTC, Neverlord commented on libcaf_net/caf/net/lp/framing.hpp
Should add `~framing() override;`

2024-03-22 15:10 UTC, Neverlord commented on libcaf_net/caf/net/web_socket/client.hpp
```suggestion

  // -- constructors, destructors, and assignment operators --------------------

  ~client() override;
```

2024-03-22 15:10 UTC, Neverlord commented on libcaf_net/caf/net/web_socket/framing.hpp
```suggestion

  // -- constructors, destructors, and assignment operators --------------------

  ~framing() override;
```

2024-03-22 15:10 UTC, Neverlord commented on libcaf_net/caf/net/web_socket/server.hpp
```suggestion

 // -- constructors, destructors, and assignment operators --------------------
 
 ~server() override;
 
```

2024-03-22 21:02 UTC, riemass commented on libcaf_net/caf/net/lp/framing.hpp
Why? Framing only has a `make` function, otherwise empty. Or do you mean `~framing_impl`?

2024-03-23 08:22 UTC, Neverlord commented on libcaf_net/caf/net/lp/framing.hpp
"otherwise empty" is precisely the reason why. `framing` inherits from two other classes and has virtual functions. So it needs a vtable. Since we don't implement any virtual function, the compiler has no place to put it (weak vtable). By overriding the destructor, we have at least one virtual member function.

2024-03-23 08:23 UTC, merged