Add tests for stringification_inspector
actor-framework/actor-framework pull request #1960
Opened 2024-11-09 19:03 UTC by shariarriday

2024-11-09 19:05 UTC, shariarriday commented
While writing the test for this file I found the following flag does not seem to have any use currently. https://github.com/actor-framework/actor-framework/blob/a4b58cac35aab8fa3df5026259fdf21b0c2211ef/libcaf_core/caf/detail/stringification_inspector.hpp#L42. It may be a good idea to remove it and do necessary refactoring if it is not required.

2024-11-11 07:43 UTC, Neverlord commented
> It may be a good idea to remove it and do necessary refactoring if it is not required.

ACK. I've made a note in #1873. Removing member variables breaks the ABI, so we can't do that change in a minor release.

2024-11-18 12:13 UTC, Neverlord requested changes
Just a couple minor tweaks for readability.

2024-11-18 12:13 UTC, Neverlord commented on libcaf_core/caf/detail/stringification_inspector.test.cpp
> +  check_eq(stringification_inspector::render(std::chrono::nanoseconds{42}),
```suggestion
  check_eq(stringification_inspector::render(42s), "42s"s);
  check_eq(stringification_inspector::render(42ms), "42ms"s);
  check_eq(stringification_inspector::render(42us), "42us"s);
  check_eq(stringification_inspector::render(42ns),
```

2024-11-18 12:13 UTC, Neverlord commented on libcaf_core/caf/detail/stringification_inspector.test.cpp
> +             reinterpret_cast<const std::byte*>("hello"), 5}),
```suggestion
  auto hello = "hello"sv;
  check_eq(stringification_inspector::render(as_bytes(make_span(hello))),
```

2024-11-24 15:41 UTC, Neverlord approved these changes

2024-11-24 15:42 UTC, merged