Send close-frame on WebSocket abort
actor-framework/actor-framework pull request #1962
Opened 2024-11-19 18:00 UTC by riemass

Closes #1938. 
We didn't ship a close frame on `websocket::framing::abort` (we did on `shutdown` but that's another story). This PR adds the missing frame. 
[According to this section in the RFC](https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.1)  the server closing the connection will send an close frame without a status code. The code will then be interpreted as 1005 by the other side. Our side can set another status code, but it's illegal to manually insert 1005 and 1006 according to [section 7.4](https://datatracker.ietf.org/doc/html/rfc6455#section-7.4). 
Also, as far as I've understood the RFC, the mask key should be present even if the payload is empty. Any message send by the client without the mask bit set will result in error, and the mask bit implies the mask key value in the frame. 

Also, there is no way to validate the closing frame in the `websocket robot` implementation. The autobahn testsuite doesn't check this, otherwise it would've shown up by now. I don't know if I should bring back the framing unit tests for this issue?

2024-11-21 18:31 UTC, Neverlord requested changes

2024-11-21 18:31 UTC, Neverlord commented on libcaf_net/caf/net/web_socket/framing.cpp
> +    ship_closing_message();
You gave some really good explanation why we sent that here without an explicit code in the PR description. I'd love to see that explanation here as code documentation. 🙂

2024-11-21 18:32 UTC, Neverlord commented
> I don't know if I should bring back the framing unit tests for this issue?

Hm, lack of testing definitely is an issue. But I don't think unit tests are the right tool. A Robot test might be better suited if we can check whether a close frame was sent or not. Can be a followup, though.

2024-11-30 09:02 UTC, riemass commented
Seems like robot can't gracefully shut down the process under windows.

2024-12-01 12:56 UTC, merged