Add tests for bool vector and fix implementation
actor-framework/actor-framework pull request #1979
Opened 2024-12-29 16:57 UTC by shariarriday

I have added a serialization/deserialization test for binary serializer. 

But, the previous implementation had a bug which caused the specialized implementation to not be executed. Due to the nature of the bug, I could not find any solution circumventing the ABI breaking changes. 
I think that we can plan to merge it in for 2.0. I am creating a draft pull request for this reason.

2025-01-18 20:09 UTC, Neverlord requested changes
It's only an ABI break because it removes the `value(std::vector<bool>& x)` overload. Bring that back and simply call that from the new `list(value(std::vector<bool>& x)` overload. Then we can merge it right away.

2025-01-18 20:09 UTC, Neverlord commented on libcaf_core/caf/serialization.test.cpp
> +    | binary_serializer   | vector_bool | true,true,false,false,true,true,true,false |
That's a bit unwindy, abbreviating it indents nicer and is less verbose:

```suggestion
    | binary_serializer   | vbool | true,true,false,false,true,true,true,false |
```

Is there a particular reason why this has 8 values? Could just have two to avoid this overly long line.

2025-01-19 19:34 UTC, shariarriday commented on libcaf_core/caf/serialization.test.cpp
> +    | binary_serializer   | vector_bool | true,true,false,false,true,true,true,false |
The serializer and deserializer use a switch case to serialize/deserialize an array into a single byte. I have added 8 entries to ensure that all conditions are being handled properly. Please let me know if it will be okay to skip it.

2025-01-20 16:49 UTC, Neverlord requested changes
Sorry, I've realized that we cannot pull this in now. It's not an ABI break, but it changes the wire format. We don't want to change our data representation on the network in a minor release.

Please split this up into one PR for the `serialization.test.cpp` additions and one PR for the fix (that will go into a v2 branch).

2025-01-21 14:58 UTC, shariarriday commented
> Sorry, I've realized that we cannot pull this in now. It's not an ABI break, but it changes the wire format. We don't want to change our data representation on the network in a minor release.
> 
> Please split this up into one PR for the `serialization.test.cpp` additions and one PR for the fix (that will go into a v2 branch).

I am not sure splitting up the tests would be beneficial. The added test will not hit the specialization for serializing boolean vectors and it will just execute the code of serializing any vectors. Maybe it will be best to include the test and code changes in a single PR for 2.x . Please let me know if you think otherwise.

2025-01-21 15:14 UTC, Neverlord commented
I think having the tests separately pulled in now is still worth it. The non-binary inspectors do a have a separate code path for `vector<bool>` that currently isn't tested. Also:

> then add a separate test for the binary serialization that consumes bool vectors of various sizes (at the very least the edge cases, i.e., 0, 1, 8, 9).

This test should still go in. For now, this test can call the `value(...)` overload for `vector<bool>` to get the coverage on that code path, ideally with a TODO reminder to use `apply` instead once we pull in the other change.

2025-01-23 16:09 UTC, Neverlord requested changes
Just one style nitpick. 👍

2025-01-23 16:09 UTC, Neverlord commented on libcaf_core/caf/serialization.test.cpp
> +        std::vector<bool> copy = {};
For keeping a consistent style:

```suggestion
        auto copy = std::vector<bool>{};
```

Same in the occurrences below.

2025-01-23 19:45 UTC, merged